dist: bionic
language: python
python:
  - 3.8

jobs:
  include:
    - os: windows
      language: shell
      env:
        - BUILD_LANG=NO
        - ISO=$ISO_NO
      before_install:
        - deployment/windows_dependencies.cmd
        - export PATH="/c/Python38:/c/Python38/Scripts:/c/Program Files/nodejs:/c/Program Files/ImageMagick-7.0.10-Q16:$PWD/bin:/c/ProgramData/chocolatey/lib/ffmpeg/tools:c/ProgramData/chocolatey/lib/OptiPNG/tools:$PATH"
      script:
        - npx gulp build-full-no

    - os: windows
      language: shell
      env:
        - BUILD_LANG=SE
        - ISO=$ISO_SE
      before_install:
        - deployment/windows_dependencies.cmd
        - export PATH="/c/Python38:/c/Python38/Scripts:/c/Program Files/nodejs:/c/Program Files/ImageMagick-7.0.10-Q16:$PWD/bin:/c/ProgramData/chocolatey/lib/ffmpeg/tools:c/ProgramData/chocolatey/lib/OptiPNG/tools:$PATH"

    - os: linux
      env:
        - BUILD_LANG=NO
        - ISO=$ISO_NO
      script:
        - npx gulp build-full-no

    - os: linux
      env:
        - BUILD_LANG=SE
        - ISO=$ISO_SE

addons:
  apt:
    packages:
      - ffmpeg
      - optipng

before_install:
  - deployment/imagemagick.sh
  - export PATH="$PWD/bin:$PATH"
  - nvm install 10

install:
  - wget -O ~/mullebil.iso $ISO
  - python -m pip install -r requirements.txt
  - python extract_iso.py ~/mullebil.iso
  - npm install

script:
  - npx gulp build-full
